
# Site
title: MDP.DevKit.LineMessaging

# theme
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Source Code on GitHub":
    - "//github.com/Clark159/MDP.DevKit.LineMessaging"
favicon_ico: "/Pages/favicon.ico"
color_scheme: dark
search_enabled: false

# Plugins
plugins:
  - jekyll-sitemap
