
# Site
title: MDP.DevKit.LineMessaging

# theme
remote_theme: pmarsceill/just-the-docs
aux_links:
  "MDP.DevKit.LineMessaging":
    - "//github.com/Clark159/MDP.DevKit.LineMessaging"
search_enabled: false
color_scheme: dark
favicon_ico: "/Pages/favicon.ico"
